### ISSUE TITLE
Bundle prevent to upgrade to symfony 6

### ISSUE THREAD

**Issue by geoffroyp** [qandidate-labs/symfony-json-request-transformer#51]
Greetings,

I'm trying to upgrade to symfony 6, but I'm getting the following message from composer:

`
  Problem 1
    - qandidate/symfony-json-request-transformer is locked to version 2.0.0 and an update of this package was not requested.
    - qandidate/symfony-json-request-transformer 2.0.0 requires symfony/http-kernel ^4.4|^5.0 -> found symfony/http-kernel[v4.4.0, ..., v4.4.36, v5.0.0, ..., v5.4.2] but these were not loaded, likely because it conflicts with another require.

`

I believe you just need to update the composer files, since I don't think there could be any breaking change from 5 to 6

**Comment by wjzijderveld** [comment]
Should be resolved via #52 
Thanks for reporting it!

**Comment by geoffroyp** [comment]
You're welcome! Thank you for your quick fix :)

However, shoudln't you publish a new release (like, 2.0.1?). 
Otherwise it forces us to use the master branch in our composer.json, which is not a very good practice...
Tons of people will switch to SF6 during the next weeks/months, so they will need a release
