### ISSUE TITLE
Dropped tolerance for null in request JSON

### ISSUE THREAD

**Issue by andrew-demb** [qandidate-labs/symfony-json-request-transformer#53]
Can you elaborate on why this check changed?
from https://github.com/qandidate-labs/symfony-json-request-transformer/blob/615f5306281a278fd8830491e4d5122b1bb5df98/src/JsonRequestTransformerListener.php#L58-L60
to https://github.com/qandidate-labs/symfony-json-request-transformer/blob/c8358385665ee44470a73243db3d2eaca16e51ae/src/JsonRequestTransformerListener.php#L54-L56

(commit https://github.com/qandidate-labs/symfony-json-request-transformer/commit/100935c332af364c2af4e2bece9462cc3a58c18e#diff-04f470cdbcc41773982a1d66ec707d1b627b609b94ccddc3649d81cd362f0c41)

Our workflow is a bit broken because of this change - we have requests with `'null'` content and this was not lead to any problems until `v2.1.0`

**Comment by wjzijderveld** [comment]
Fixed in #54 and released in [2.1.1](https://github.com/qandidate-labs/symfony-json-request-transformer/releases/tag/2.1.1)

Thanks for flagging this!
